-- Base revisada a partir do schema enviado. Execute no Supabase SQL Editor.
create extension if not exists "pgcrypto";

do $$ begin create type user_role as enum ('MASTER_ADMIN','CLIENT'); exception when duplicate_object then null; end $$;
do $$ begin create type user_status as enum ('ACTIVE','SUSPENDED','BLOCKED'); exception when duplicate_object then null; end $$;
do $$ begin create type subscription_status as enum ('ACTIVE','PENDING','EXPIRING','EXPIRED','SUSPENDED','CANCELLED'); exception when duplicate_object then null; end $$;
do $$ begin create type loan_status as enum ('ACTIVE','PARTIAL','NEAR_DUE','OVERDUE','PAID','ARCHIVED'); exception when duplicate_object then null; end $$;
do $$ begin create type adjustment_type as enum ('ADD_PRINCIPAL','REDUCE_PRINCIPAL','ADMIN_ADJUSTMENT'); exception when duplicate_object then null; end $$;
do $$ begin create type payment_method as enum ('PIX','DINHEIRO','TRANSFERENCIA','CARTAO','OUTRO'); exception when duplicate_object then null; end $$;

create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text not null,email text not null unique,role user_role not null default 'CLIENT',status user_status not null default 'ACTIVE',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.plans(id uuid primary key default gen_random_uuid(),name text not null,description text,price numeric(12,2) not null check(price>=0),period_days int not null default 30 check(period_days>0),max_loans int,max_people int,features jsonb not null default '[]'::jsonb,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.subscriptions(id uuid primary key default gen_random_uuid(),profile_id uuid not null unique references public.profiles(id) on delete cascade,plan_id uuid not null references public.plans(id),status subscription_status not null default 'PENDING',price numeric(12,2) not null check(price>=0),started_at timestamptz not null default now(),due_date date not null,last_payment_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.subscription_payments(id uuid primary key default gen_random_uuid(),subscription_id uuid not null references public.subscriptions(id) on delete cascade,amount numeric(12,2) not null check(amount>0),payment_date date not null default current_date,period_start date not null,period_end date not null,method text not null default 'MANUAL',notes text,created_by uuid references public.profiles(id),created_at timestamptz not null default now());
create table if not exists public.settings(key text primary key,value jsonb not null,updated_at timestamptz not null default now(),updated_by uuid references public.profiles(id));
create table if not exists public.people(id uuid primary key default gen_random_uuid(),profile_id uuid not null references public.profiles(id) on delete cascade,name text not null,document text,phone text,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create sequence if not exists public.loan_friendly_id_seq start 1;
create table if not exists public.loans(id uuid primary key default gen_random_uuid(),friendly_id text not null unique,profile_id uuid not null references public.profiles(id) on delete cascade,person_id uuid not null references public.people(id),operation_date date not null,principal_initial numeric(14,2) not null check(principal_initial>0),principal_current numeric(14,2) not null check(principal_current>=0),rate_type text not null default 'PERCENT_MONTHLY',rate_value numeric(8,4) not null check(rate_value>=0),due_date date not null,status loan_status not null default 'ACTIVE',notes text,archived boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.loan_periods(id uuid primary key default gen_random_uuid(),loan_id uuid not null references public.loans(id) on delete cascade,start_date date not null,end_date date not null,base_principal numeric(14,2) not null check(base_principal>=0),configured_rule jsonb not null,calculated_charge numeric(14,2) not null check(calculated_charge>=0),amount_paid numeric(14,2) not null default 0 check(amount_paid>=0),remaining_charge numeric(14,2) not null check(remaining_charge>=0),status text not null default 'OPEN',created_at timestamptz not null default now());
create table if not exists public.payments(id uuid primary key default gen_random_uuid(),loan_id uuid not null references public.loans(id) on delete cascade,loan_period_id uuid references public.loan_periods(id),total_amount numeric(14,2) not null check(total_amount>0),charge_amount numeric(14,2) not null default 0 check(charge_amount>=0),principal_amount numeric(14,2) not null default 0 check(principal_amount>=0),payment_date date not null default current_date,payment_method payment_method not null default 'OUTRO',notes text,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),constraint chk_payment_split check(total_amount=charge_amount+principal_amount));
create table if not exists public.loan_adjustments(id uuid primary key default gen_random_uuid(),loan_id uuid not null references public.loans(id) on delete cascade,type adjustment_type not null,amount numeric(14,2) not null check(amount>0),previous_balance numeric(14,2) not null,new_balance numeric(14,2) not null check(new_balance>=0),reason text,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now());
create table if not exists public.audit_logs(id uuid primary key default gen_random_uuid(),profile_id uuid references public.profiles(id),action text not null,entity text not null,entity_id uuid,field text,old_value text,new_value text,reason text,created_at timestamptz not null default now());
create table if not exists public.email_logs(id uuid primary key default gen_random_uuid(),recipient text not null,type text not null,status text not null default 'PENDING',error text,related_entity text,related_id uuid,created_at timestamptz not null default now());

insert into public.plans(name,description,price,period_days,is_active) select 'Profissional','Plano padrão da plataforma',40,30,true where not exists(select 1 from public.plans where name='Profissional');
insert into public.settings(key,value) values ('grace_period_days','3'),('near_due_days','3'),('admin_email','"paulohp.silva99@gmail.com"'),('daily_summary_enabled','false'),('daily_summary_time','"08:00"') on conflict(key) do nothing;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,full_name,email,role,status) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),new.email,'CLIENT','ACTIVE'); return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.is_master_admin() returns boolean language sql security definer stable set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='MASTER_ADMIN' and status='ACTIVE'); $$;

create or replace function public.protect_profile_privileges() returns trigger language plpgsql security definer set search_path=public as $$ begin if auth.uid() is null then return new; end if; if not public.is_master_admin() and auth.uid()=old.id then if new.role is distinct from old.role or new.status is distinct from old.status then raise exception 'role/status can only be changed by MASTER_ADMIN'; end if; end if; return new; end; $$;
drop trigger if exists trg_protect_profile_privileges on public.profiles; create trigger trg_protect_profile_privileges before update on public.profiles for each row execute function public.protect_profile_privileges();
revoke all on function public.is_master_admin() from public; grant execute on function public.is_master_admin() to authenticated;

create or replace function public.set_loan_friendly_id() returns trigger language plpgsql as $$ begin new.friendly_id:='EMP-'||lpad(nextval('public.loan_friendly_id_seq')::text,6,'0'); return new; end; $$;
drop trigger if exists trg_loan_friendly_id on public.loans; create trigger trg_loan_friendly_id before insert on public.loans for each row execute function public.set_loan_friendly_id();

create or replace function public.validate_loan_person_owner() returns trigger language plpgsql security definer set search_path=public as $$ begin if not exists(select 1 from public.people p where p.id=new.person_id and p.profile_id=new.profile_id) then raise exception 'person does not belong to loan owner'; end if; return new; end; $$;
drop trigger if exists trg_validate_loan_person_owner on public.loans; create trigger trg_validate_loan_person_owner before insert or update on public.loans for each row execute function public.validate_loan_person_owner();

alter table public.profiles enable row level security; alter table public.plans enable row level security; alter table public.subscriptions enable row level security; alter table public.subscription_payments enable row level security; alter table public.settings enable row level security; alter table public.people enable row level security; alter table public.loans enable row level security; alter table public.loan_periods enable row level security; alter table public.payments enable row level security; alter table public.loan_adjustments enable row level security; alter table public.audit_logs enable row level security; alter table public.email_logs enable row level security;

drop policy if exists profiles_select on public.profiles; create policy profiles_select on public.profiles for select to authenticated using(id=auth.uid() or public.is_master_admin());
drop policy if exists profiles_update on public.profiles; create policy profiles_update on public.profiles for update to authenticated using(id=auth.uid() or public.is_master_admin()) with check(id=auth.uid() or public.is_master_admin());
drop policy if exists plans_select on public.plans; create policy plans_select on public.plans for select to authenticated using(is_active=true or public.is_master_admin());
drop policy if exists plans_admin on public.plans; create policy plans_admin on public.plans for all to authenticated using(public.is_master_admin()) with check(public.is_master_admin());
drop policy if exists subscriptions_select on public.subscriptions; create policy subscriptions_select on public.subscriptions for select to authenticated using(profile_id=auth.uid() or public.is_master_admin());
drop policy if exists subscriptions_admin on public.subscriptions; create policy subscriptions_admin on public.subscriptions for all to authenticated using(public.is_master_admin()) with check(public.is_master_admin());
drop policy if exists people_owner on public.people; create policy people_owner on public.people for all to authenticated using(profile_id=auth.uid() or public.is_master_admin()) with check(profile_id=auth.uid() or public.is_master_admin());
drop policy if exists loans_owner on public.loans; create policy loans_owner on public.loans for all to authenticated using(profile_id=auth.uid() or public.is_master_admin()) with check(profile_id=auth.uid() or public.is_master_admin());
drop policy if exists periods_owner on public.loan_periods; create policy periods_owner on public.loan_periods for all to authenticated using(public.is_master_admin() or exists(select 1 from public.loans l where l.id=loan_id and l.profile_id=auth.uid())) with check(public.is_master_admin() or exists(select 1 from public.loans l where l.id=loan_id and l.profile_id=auth.uid()));
drop policy if exists payments_owner on public.payments; create policy payments_owner on public.payments for all to authenticated using(public.is_master_admin() or exists(select 1 from public.loans l where l.id=loan_id and l.profile_id=auth.uid())) with check(public.is_master_admin() or exists(select 1 from public.loans l where l.id=loan_id and l.profile_id=auth.uid()));
drop policy if exists adjustments_owner on public.loan_adjustments; create policy adjustments_owner on public.loan_adjustments for all to authenticated using(public.is_master_admin() or exists(select 1 from public.loans l where l.id=loan_id and l.profile_id=auth.uid())) with check(public.is_master_admin() or exists(select 1 from public.loans l where l.id=loan_id and l.profile_id=auth.uid()));
drop policy if exists subpayments_select on public.subscription_payments; create policy subpayments_select on public.subscription_payments for select to authenticated using(public.is_master_admin() or exists(select 1 from public.subscriptions s where s.id=subscription_id and s.profile_id=auth.uid()));
drop policy if exists subpayments_admin on public.subscription_payments; create policy subpayments_admin on public.subscription_payments for all to authenticated using(public.is_master_admin()) with check(public.is_master_admin());
drop policy if exists settings_admin on public.settings; create policy settings_admin on public.settings for all to authenticated using(public.is_master_admin()) with check(public.is_master_admin());
drop policy if exists audit_select on public.audit_logs; create policy audit_select on public.audit_logs for select to authenticated using(profile_id=auth.uid() or public.is_master_admin());
drop policy if exists email_admin on public.email_logs; create policy email_admin on public.email_logs for all to authenticated using(public.is_master_admin()) with check(public.is_master_admin());

-- Bootstrap: execute MANUALLY once in SQL Editor after creating the owner's Auth user.
-- update public.profiles set role='MASTER_ADMIN' where email='paulohp.silva99@gmail.com';
