'use client'
import {useState} from 'react'
import {ArrowRight,LockKeyhole,Mail,UserRound} from 'lucide-react'
import Link from 'next/link'
import {createClient} from '@/lib/supabase/client'

export default function Cadastro(){
 const [name,setName]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');const [loading,setLoading]=useState(false)
 async function submit(e:React.FormEvent){e.preventDefault();setError('');setMessage('');if(password.length<8||password!==confirm){setError('A senha precisa ter pelo menos 8 caracteres e as duas senhas devem ser iguais.');return}setLoading(true);const supabase=createClient();const {error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name},emailRedirectTo:`${window.location.origin}/auth/confirm?next=/dashboard`}});if(error)setError(error.message.includes('already')?'Este e-mail já está cadastrado.':'Não foi possível criar sua conta.');else setMessage('Conta criada. Verifique seu e-mail para confirmar o acesso.');setLoading(false)}
 return <main className="auth-page"><div className="auth-card"><div className="auth-brand">Controle<span>.Financeiro</span></div><div className="auth-country">🇧🇷 Português do Brasil · R$</div><h1>Criar sua conta</h1><p className="muted">Comece a organizar sua carteira de forma profissional.</p><form onSubmit={submit} className="auth-form"><label className="label">Nome<div className="input-icon"><UserRound size={17}/><input className="input" style={{paddingLeft:40}} value={name} onChange={e=>setName(e.target.value)} required placeholder="Seu nome"/></div></label><label className="label">E-mail<div className="input-icon"><Mail size={17}/><input className="input" style={{paddingLeft:40}} type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="voce@email.com"/></div></label><label className="label">Senha<div className="input-icon"><LockKeyhole size={17}/><input className="input" style={{paddingLeft:40}} type="password" value={password} onChange={e=>setPassword(e.target.value)} required placeholder="Mínimo de 8 caracteres"/></div></label><label className="label">Confirmar senha<input className="input" type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} required/></label>{error&&<div className="alert error">{error}</div>}{message&&<div className="alert success">{message}</div>}<button className="btn btn-primary" style={{width:'100%'}} disabled={loading}>{loading?'Criando conta...':'Criar conta'}<ArrowRight size={17}/></button></form><p className="auth-foot">Já possui uma conta? <Link className="link" href="/login">Entrar</Link></p></div></main>
}
