import {redirect} from 'next/navigation'
import {createClient} from '@/lib/supabase/server'
import Link from 'next/link'
const brl=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const subLabel:any={ACTIVE:'Ativa',PENDING:'Pendente',EXPIRING:'Expirando',EXPIRED:'Expirada',SUSPENDED:'Suspensa',CANCELLED:'Cancelada'}
export default async function ClientesAdmin(){
 const s=await createClient(); const {data:{user}}=await s.auth.getUser(); if(!user)redirect('/login');
 const {data:p}=await s.from('profiles').select('role').eq('id',user.id).single(); if(p?.role!=='MASTER_ADMIN')redirect('/dashboard');
 const {data:clientsData}=await s.from('profiles').select('id,full_name,email,status,created_at').eq('role','CLIENT').order('created_at',{ascending:false});
 const clients=clientsData??[];
 const ids=clients.map((c:any)=>c.id); const {data:subs=[]}=ids.length?await s.from('subscriptions').select('id,profile_id,status,price,due_date,plans(name)').in('profile_id',ids).order('due_date',{ascending:false}):{data:[]};
 const latest=new Map<string,any>(); for(const sub of subs||[]) if(!latest.has(sub.profile_id)) latest.set(sub.profile_id,sub);
 return <div className="container"><div className="page-title"><div><h1>Clientes</h1><p className="muted">Controle de acesso, assinatura e situação de cada cliente.</p></div></div><div className="card" style={{padding:10}}><div className="table-wrap"><table className="table"><thead><tr><th>Cliente</th><th>Plano</th><th>Assinatura</th><th>Vencimento</th><th>Conta</th><th>Ações</th></tr></thead><tbody>{clients.map((c:any)=>{const sub=latest.get(c.id);return <tr key={c.id}><td><strong>{c.full_name||'Sem nome'}</strong><div className="muted" style={{fontSize:12}}>{c.email}</div></td><td>{sub?.plans?.name||'—'}<div className="muted">{sub?brl(Number(sub.price)):''}</div></td><td><span className={`badge ${sub?.status==='ACTIVE'?'green':sub?.status==='EXPIRING'?'amber':'red'}`}>{subLabel[sub?.status]||'Sem assinatura'}</span></td><td>{sub?.due_date?new Date(sub.due_date+'T12:00:00').toLocaleDateString('pt-BR'):'—'}</td><td><span className={`badge ${c.status==='ACTIVE'?'green':'red'}`}>{c.status==='ACTIVE'?'Ativa':c.status==='SUSPENDED'?'Suspensa':'Bloqueada'}</span></td><td><div style={{display:'flex',gap:7,flexWrap:'wrap'}}><form action="/api/admin/subscription" method="post"><input type="hidden" name="profile_id" value={c.id}/><input type="hidden" name="action" value="activate"/><button className="btn" type="submit">+30 dias</button></form><form action="/api/admin/subscription" method="post"><input type="hidden" name="profile_id" value={c.id}/><input type="hidden" name="action" value="suspend"/><button className="btn" type="submit">Suspender</button></form></div></td></tr>})}</tbody></table>{clients.length===0&&<div className="empty">Nenhum cliente cadastrado.</div>}</div></div><div className="card" style={{padding:18,marginTop:18}}><strong>Modo de teste do Master</strong><p className="muted" style={{marginBottom:0}}>“+30 dias” ativa a assinatura manualmente para testes. Quando o Mercado Pago entrar, essa atualização será feita automaticamente pelo webhook.</p></div><Link href="/admin" className="link" style={{display:'inline-block',marginTop:16}}>← Voltar ao painel</Link></div>
}

