 'use client'
import { useEffect,useMemo,useState } from 'react'
import { useParams,useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
export default function EditarOperacao(){
 const {id}=useParams<{id:string}>(); const router=useRouter(); const supabase=useMemo(()=>createClient(),[])
 const [loan,setLoan]=useState<any>(null); const [people,setPeople]=useState<any[]>([]); const [form,setForm]=useState<any>({}); const [saving,setSaving]=useState(false); const [error,setError]=useState('')
 useEffect(()=>{(async()=>{const [{data:l,error:le},{data:ps}]=await Promise.all([supabase.from('loans').select('*').eq('id',id).single(),supabase.from('people').select('id,name').order('name')]);if(le){setError('Não foi possível carregar a operação.');return}setLoan(l);setForm({person_id:l.person_id,operation_date:l.operation_date,principal_current:String(l.principal_current).replace('.',','),rate_value:String(l.rate_value).replace('.',','),due_date:l.due_date,notes:l.notes||''});setPeople(ps||[])})()},[id,supabase])
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');const value=Number(String(loan.principal_current).replace(',','.'));const rate=Number(String(form.rate_value).replace(',','.'));if(!(value>=0)||rate<0||!form.person_id||!form.due_date){setError('Confira os campos obrigatórios.');setSaving(false);return}const {error}=await supabase.from('loans').update({person_id:form.person_id,operation_date:form.operation_date,rate_value:rate,due_date:form.due_date,notes:form.notes||null}).eq('id',id);if(error)setError(error.message);else router.push(`/operacoes/${id}`);setSaving(false)}
 if(error&&!loan)return <div className="container"><div className="card" style={{padding:24}}><p className="red">{error}</p></div></div>
 if(!loan)return <div className="container"><div className="card" style={{padding:24}}>Carregando...</div></div>
 return <div className="container"><div className="page-title"><div><div className="muted" style={{fontWeight:800}}>{loan.friendly_id}</div><h1>Editar operação</h1><p className="muted">Todos os campos operacionais podem ser ajustados. O histórico de pagamentos permanece preservado.</p></div></div><form onSubmit={save} className="card" style={{padding:24,maxWidth:900}}><div className="form-grid"><label className="label">Pessoa<select className="select" value={form.person_id} onChange={e=>setForm({...form,person_id:e.target.value})}>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="label">Data<input className="input" type="date" value={form.operation_date} onChange={e=>setForm({...form,operation_date:e.target.value})}/></label><label className="label">Principal atual<input className="input" inputMode="decimal" value={form.principal_current} readOnly/><span className="muted small">Para adicionar ou reduzir saldo, use “Movimentar principal” na tela da operação. Assim o histórico permanece íntegro.</span></label><label className="label">Taxa mensal (%)<input className="input" inputMode="decimal" value={form.rate_value} onChange={e=>setForm({...form,rate_value:e.target.value})}/></label><label className="label">Vencimento<input className="input" type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/></label><label className="label full">Observações<textarea className="textarea" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div>{error&&<p className="red">{error}</p>}<div className="notice">O valor do principal pode ser editado diretamente, mas alterações que representem acréscimo/redução devem preferencialmente ser registradas como movimentação para manter a auditoria completa.</div><div style={{display:'flex',justifyContent:'flex-end',gap:10,marginTop:18}}><button type="button" className="btn btn-secondary" onClick={()=>router.back()}>Cancelar</button><button className="btn btn-primary" disabled={saving}>{saving?'Salvando...':'Salvar alterações'}</button></div></form></div>
}

