'use client'
import {useState} from 'react'
import {useRouter} from 'next/navigation'
import {createClient} from '@/lib/supabase/client'
const brl=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
export default function AdjustmentForm({loanId,principal}:{loanId:string;principal:number}){
 const supabase=createClient();const router=useRouter();const [type,setType]=useState<'ADD_PRINCIPAL'|'REDUCE_PRINCIPAL'>('ADD_PRINCIPAL');const [amount,setAmount]=useState('');const [reason,setReason]=useState('');const [error,setError]=useState('');const [saving,setSaving]=useState(false)
 async function submit(e:React.FormEvent){e.preventDefault();setError('');const value=Number(amount.replace(',','.'));if(!(value>0)){setError('Informe um valor válido.');return}if(type==='REDUCE_PRINCIPAL'&&value>principal){setError('A redução não pode superar o saldo atual.');return}setSaving(true);const {error}=await supabase.rpc('adjust_loan_principal',{p_loan_id:loanId,p_type:type,p_amount:value,p_reason:reason||null});if(error)setError(error.message);else{setAmount('');setReason('');router.refresh()}setSaving(false)}
 return <form onSubmit={submit} className="card" style={{padding:20}}><div className="panel-head"><div><h2>Movimentar principal</h2><p className="muted">Registre acréscimos ou reduções sem perder a auditoria.</p></div></div><div style={{display:'grid',gap:13}}><label className="label">Movimentação<select className="select" value={type} onChange={e=>setType(e.target.value as any)}><option value="ADD_PRINCIPAL">Adicionar ao principal</option><option value="REDUCE_PRINCIPAL">Reduzir o principal</option></select></label><label className="label">Valor<input className="input" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="200,00" required/></label><label className="label">Motivo <span className="muted" style={{fontWeight:400}}>(recomendado)</span><input className="input" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Ex.: novo valor liberado"/></label><div className="notice">Saldo atual: <strong>{brl(principal)}</strong></div>{error&&<div className="red">{error}</div>}<button className="btn btn-secondary" disabled={saving}>{saving?'Registrando...':'Registrar movimentação'}</button></div></form>
}
