'use client'
import {useState} from 'react'
import {useRouter} from 'next/navigation'
import {createClient} from '@/lib/supabase/client'
import {LockKeyhole,Mail,ArrowRight} from 'lucide-react'
export default function Login(){
 const router=useRouter()
 const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(false)
 async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setError('');const {error}=await createClient().auth.signInWithPassword({email,password});if(error)setError('E-mail ou senha inválidos.');else router.replace('/dashboard');setLoading(false)}
 return <main style={{minHeight:'100vh',display:'grid',placeItems:'center',padding:20,background:'radial-gradient(circle at top right,#dff2e6 0,#f4f7f5 42%,#eef3ef 100%)'}}><div style={{width:'100%',maxWidth:980,display:'grid',gridTemplateColumns:'1fr 420px',gap:20,alignItems:'stretch'}} className="login-grid"><section className="card" style={{padding:40,background:'#10251a',color:'#fff',display:'flex',flexDirection:'column',justifyContent:'space-between',minHeight:520}}><div><div style={{fontSize:28,fontWeight:900}}>Controle<span style={{opacity:.5}}>.Financeiro</span></div><div style={{marginTop:45,fontSize:38,fontWeight:900,lineHeight:1.05,letterSpacing:'-.04em'}}>Seu controle financeiro, simples e profissional.</div><p style={{color:'#bfd1c5',fontSize:16,lineHeight:1.6,maxWidth:470}}>Organize pessoas, operações, pagamentos, saldos e vencimentos em um único lugar.</p></div><div style={{color:'#bfd1c5'}}>🇧🇷 Português do Brasil · Valores em R$</div></section><form onSubmit={submit} className="card" style={{padding:32,alignSelf:'center'}}><div style={{fontSize:13,color:'var(--green)',fontWeight:800}}>BEM-VINDO DE VOLTA</div><h1 style={{margin:'7px 0 5px'}}>Entrar</h1><p className="muted" style={{marginTop:0}}>Acesse sua conta com segurança.</p><div style={{display:'grid',gap:16,marginTop:24}}><label className="label"><span>E-mail</span><div style={{position:'relative'}}><Mail size={17} style={{position:'absolute',left:12,top:13,color:'#7b867f'}}/><input className="input" style={{paddingLeft:40}} value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="seu@email.com" required/></div></label><label className="label"><span>Senha</span><div style={{position:'relative'}}><LockKeyhole size={17} style={{position:'absolute',left:12,top:13,color:'#7b867f'}}/><input className="input" style={{paddingLeft:40}} value={password} onChange={e=>setPassword(e.target.value)} type="password" required/></div></label></div>{error&&<div className="card" style={{marginTop:15,padding:12,borderColor:'#fecaca',background:'#fff7f7',color:'#991b1b'}}>{error}</div>}<button className="btn btn-primary" style={{width:'100%',marginTop:20}} disabled={loading}>{loading?'Entrando...':'Entrar'}<ArrowRight size={17}/></button><div style={{textAlign:'center',marginTop:14}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><a className="link" href="/recuperar-senha">Esqueci minha senha</a><a className="link" href="/cadastro">Criar conta</a></div></div><p className="muted" style={{fontSize:12,textAlign:'center',marginTop:18}}>Acesso protegido pelo Supabase Auth.</p></form></div><style jsx>{`@media(max-width:800px){.login-grid{grid-template-columns:1fr!important}.login-grid section{display:none}}`}</style></main>
}

