'use client'
import {useCallback,useEffect,useMemo,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
const empty={name:'',phone:''}
export default function Pessoas(){const supabase=useMemo(()=>createClient(),[]);const [people,setPeople]=useState<any[]>([]);const [form,setForm]=useState(empty);const [editing,setEditing]=useState<string|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('')
 const load=useCallback(async()=>{setLoading(true);const {data}=await supabase.from('people').select('id,name,phone,created_at').order('created_at',{ascending:false});setPeople(data||[]);setLoading(false)},[supabase])
 useEffect(()=>{void load()},[load])
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');if(!form.name.trim()){setError('Informe o nome.');setSaving(false);return}const payload={name:form.name.trim(),phone:form.phone.trim()||null};const q=editing?supabase.from('people').update(payload).eq('id',editing):supabase.from('people').insert(payload);const {error}=await q;if(error)setError(error.message);else{setForm(empty);setEditing(null);await load()}setSaving(false)}
 function edit(p:any){setEditing(p.id);setForm({name:p.name,phone:p.phone||''});window.scrollTo({top:0,behavior:'smooth'})}
 return <div className="container"><div className="page-title"><div><div className="eyebrow-dark">CADASTRO</div><h1>Pessoas</h1><p className="muted">Mantenha seus contatos organizados e vinculados às operações.</p></div></div><div className="grid grid-2"><form onSubmit={save} className="card" style={{padding:22}}><div className="panel-head"><div><h2>{editing?'Editar pessoa':'Nova pessoa'}</h2><p className="muted">{editing?'Atualize os dados sem perder o histórico.':'Cadastre somente o necessário.'}</p></div></div><div style={{display:'grid',gap:15}}><label className="label">Nome<input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Nome completo" required/></label><label className="label">Telefone <span className="muted" style={{fontWeight:400}}>(opcional)</span><input className="input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="(21) 99999-9999"/></label>{error&&<div className="red">{error}</div>}<div style={{display:'flex',gap:9}}><button className="btn btn-primary" disabled={saving}>{saving?'Salvando...':editing?'Salvar alterações':'Cadastrar pessoa'}</button>{editing&&<button type="button" className="btn btn-secondary" onClick={()=>{setEditing(null);setForm(empty);setError('')}}>Cancelar</button>}</div></div></form><div className="card" style={{padding:10}}><div style={{padding:'10px 12px'}}><h2 style={{margin:0}}>Pessoas cadastradas</h2><p className="muted" style={{margin:'5px 0'}}>Use Editar para atualizar os dados.</p></div>{loading?<div className="empty">Carregando...</div>:people.length===0?<div className="empty">Nenhuma pessoa cadastrada.</div>:<div className="table-wrap"><table className="table" style={{minWidth:600}}><thead><tr><th>Nome</th><th>Telefone</th><th>Cadastro</th><th></th></tr></thead><tbody>{people.map(p=><tr key={p.id}><td><strong>{p.name}</strong></td><td>{p.phone||'—'}</td><td>{new Date(p.created_at).toLocaleDateString('pt-BR')}</td><td><div style={{display:'flex',gap:8}}><button className="btn btn-secondary" onClick={()=>edit(p)}>Editar</button></div></td></tr>)}</tbody></table></div>}</div></div></div>}

