'use client'
import {useEffect,useMemo,useState} from 'react'
import {useRouter} from 'next/navigation'
import {createClient} from '@/lib/supabase/client'
export default function NovaOperacao(){const supabase=useMemo(()=>createClient(),[]);const router=useRouter();const [people,setPeople]=useState<any[]>([]);const [personId,setPersonId]=useState('');const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [principal,setPrincipal]=useState('');const [rate,setRate]=useState('20');const [due,setDue]=useState('');const [notes,setNotes]=useState('');const [saving,setSaving]=useState(false);const [error,setError]=useState('')
 useEffect(()=>{supabase.from('people').select('id,name').order('name').then(({data})=>setPeople(data||[]))},[supabase])
 async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');const {data:{user}}=await supabase.auth.getUser();if(!user){setError('Sessão expirada.');setSaving(false);return}if(!personId){setError('Selecione uma pessoa.');setSaving(false);return}const value=Number(principal.replace(',','.'));const r=Number(rate.replace(',','.'));if(!(value>0)||r<0||!due){setError('Confira os valores e o vencimento.');setSaving(false);return}const {data,error}=await supabase.from('loans').insert({profile_id:user.id,person_id:personId,operation_date:date,principal_initial:value,principal_current:value,rate_type:'PERCENT_MONTHLY',rate_value:r,due_date:due,notes:notes||null}).select('id').single();if(error){setError(error.message)}else if(data){await supabase.rpc('create_loan_period',{p_loan_id:data.id,p_start:date,p_end:due});router.push(`/operacoes/${data.id}`)}setSaving(false)}
 return <div className="container"><div className="page-title"><div><h1>Nova operação</h1><p className="muted">Preencha apenas o necessário. O sistema calcula e registra o restante.</p></div></div><form onSubmit={submit} className="card" style={{padding:24,maxWidth:900}}><div className="form-grid"><label className="label">Pessoa<select className="select" value={personId} onChange={e=>setPersonId(e.target.value)} required><option value="">Selecione...</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="label">Data da operação<input className="input" type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><label className="label">Valor principal<input className="input" inputMode="decimal" value={principal} onChange={e=>setPrincipal(e.target.value)} placeholder="300,00" required/></label><label className="label">Taxa mensal (%)<input className="input" inputMode="decimal" value={rate} onChange={e=>setRate(e.target.value)} placeholder="20" required/></label><label className="label">Data de vencimento<input className="input" type="date" value={due} onChange={e=>setDue(e.target.value)} required/></label><label className="label full">Observações <span className="muted" style={{fontWeight:400}}>(opcional)</span><textarea className="textarea" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Observações internas..."/></label></div>{error&&<p className="red">{error}</p>}<div style={{display:'flex',justifyContent:'flex-end',gap:10,marginTop:20}}><button type="button" className="btn btn-secondary" onClick={()=>router.back()}>Cancelar</button><button className="btn btn-primary" disabled={saving}>{saving?'Salvando...':'Criar operação'}</button></div></form></div>}

